function add_drowsiness_randelectrode(task_id, max_task_id, randpath, datapath, performancepath, savepath, savename)
    %loads a list of randomly generated electrode pairs, add drowsiness and
    %performance data to existing data generated by main_randelectrode.m
    rand_electrodes = readmatrix(sprintf('%srand_electrode_list.csv', randpath));
    length = size(rand_electrodes);
    max_i = task_id*length(1)/max_task_id;
    min_i = (task_id - 1)*length(1)/max_task_id + 1;
    for index = min_i:1:max_i
        try
            add_drowsiness_automated(datapath, rand_electrodes(index,2), rand_electrodes(index,3), performancepath, savepath, savename)
    
        catch err
            disp(err)
        end
    end